options:
  aci-repo:
    type: string
    default: 'deb http://a.b.c.d'
    description: "Apt repository for ACI module"
  aci-repo-key:
    type: string
    default:
    description: "Repo key, if missing no package authentication will be performed"
  aci-apic-hosts:
    type: string
    default: 1.1.1.1
    description: "comma separated string of apic hostnames or ip addresses"
  aci-apic-username:
    type: string
    default: admin
    description: "APIC username"
  aci-apic-password:
    type: string
    default: password
    description: "APIC password"
  aci-apic-system-id:
    type: string
    default: 'openstack'
    description: "As id string for this openstack instance"
  aci-aim-system-id:
    type: string
    default: ''
    description: |
        An id string for this aim instance, this should not be set unless specifically required for
        upgrade from older versions. In all other cases this will be automatcally set to the
        value of apic-system-id
  aci-apic-entity-profile:
    type: string
    default: 'openstack'
    description: "ACI Attached Entity Profile that is configured on fabric, where the nodes are connected"
  aci-encap:
    type: string
    default: vxlan
    description: "vlan or vxlan"
  aci-vlan-ranges:
    type: string
    default: 1000:1010
    description: "Vlan range to use when aci_encap for vmm domain in of type vlan"
  aci-connection-json:
    type: string
    default:
    description: |
        Describe nova-compute connections to ACI leaf in JSON format. 
        Example {'101': ['host1.domain:1/1', 'host2.domain:1/2'], '102':['host3.domain:1/4']} 
        101 is the switch id, host1.domain is connected to port 1/1 
  aci-vpc-pairs:
    type: string
    default:
    description: |
        If using VPC to connect the nodes to ACI leaf switches, specify the switch id pairs for vpc. 
        Example, if switch ids 101 and 102 form a vpc pair and switch ids 103, 104 form a vpc pair, then set the value to '101:102,103:104'"
  aci-enable-optimized-metadata:
    type: boolean
    default: True
    description: "enable optimized metadata"
  aci-default-opflex-physnet:
    type: string
    default: physnet1
    description: "Default physnet for opflex type networks"
  aci-enable-sfc:
    type: boolean
    default: False
    description: "Enable neutron sfc extensions"
  aci-external-l3-domain:
    type: string
    default:
    description: "Defaulf external routed domain to attach to l3out (SVI)"
  aci-mechanism-drivers:
    type: string
    default: apic_aim
    description:
  aci-group-policy-policy-drivers:
    type: string
    default: aim_mapping
    description:
  aci-group-policy-extension-drivers:
    type: string
    default: aim_extension,proxy_group,apic_allowed_vm_name,apic_segmentation_label
    description:
  aci-ml2-type-drivers:
    type: string
    default: opflex,local,vlan,vxlan,flat,gre
    description:
  aci-ml2-extension-drivers:
    type: string
    default: apic_aim,port_security
    description:
  aci-tenant-network-types:
    type: string
    default: opflex
    description:
  aci-neutron-service-plugins:
    type: string
    default: group_policy,ncp,apic_aim_l3
    description:
  neutron-vlan-ranges:
    type: string
    default:
    description: define neutron vlan ranges to use in case of hierarchical port binding scenario. The format is physnet0:1:100,physnet1:200:210
  aci-physnet-host-mapping:
    type: string
    default:
    description: |
       If using physnets and to map hosts to physnets use the following format. Example '{"physnet0": "host1:e1:e2,host2:e3", "physnet1":"host1:e4:e5:e6"}'
  aci-disable-vmdom:
    type: boolean
    default: False
    description: By default a VM domain is created. In some cases user may want to disable the creation of the same.
  aci-physdom-id:
    type: string
    default:
    description: Set the value, when using physdom's instead of VMM domains. Suggested value is the value set for aci-apic-system-id
  rabbit-user:
    default: neutron
    type: string
    description: Username used to access RabbitMQ queue
  rabbit-vhost:
    default: openstack
    type: string
    description: RabbitMQ vhost
  database-user:
    default: neutron
    type: string
    description: Username for Neutron database access (if enabled)
  database:
    default: neutron
    type: string
    description: Database name for Neutron (if enabled)
